from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(Ui_MainWindow, self).__init__()



    def setIPAndPassword(self, IP, password):

        self.publicIP = IP
        self.password = password
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget_Main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_Main.setGeometry(QtCore.QRect(0, 50, 801, 521))
        self.stackedWidget_Main.setObjectName("stackedWidget_Main")
        self.stackedWidget_Main_page_1 = QtWidgets.QWidget()
        self.stackedWidget_Main_page_1.setObjectName("stackedWidget_Main_page_1")
        self.stackedWidget_Main.addWidget(self.stackedWidget_Main_page_1)
        self.stackedWidget_Main_page_2 = QtWidgets.QWidget()
        self.stackedWidget_Main_page_2.setObjectName("stackedWidget_Main_page_2")
        self.main_p2_btn_settings = QtWidgets.QPushButton(self.stackedWidget_Main_page_2)
        self.main_p2_btn_settings.setGeometry(QtCore.QRect(710, 460, 51, 51))
        self.main_p2_btn_settings.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n""")
        self.main_p2_btn_settings.setText("")
        icon = QtGui.QIcon()


        # set icons_settings.png path from your device
        icon.addPixmap(QtGui.QPixmap(os.getcwd()+"./Icons/icons_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_p2_btn_settings.setIcon(icon)
        self.main_p2_btn_settings.setIconSize(QtCore.QSize(50, 50))
        self.main_p2_btn_settings.setObjectName("main_p2_btn_settings")
        self.main_p2_frame = QtWidgets.QFrame(self.stackedWidget_Main_page_2)
        self.main_p2_frame.setGeometry(QtCore.QRect(210, 120, 370, 200))
        self.main_p2_frame.setStyleSheet("background-color: rgba(255, 255, 255, 1);\n""border-radius: 25px;\n""")
        self.main_p2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_p2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_p2_frame.setObjectName("main_p2_frame")
        self.main_p2_label_text_credentials = QtWidgets.QLabel(self.main_p2_frame)
        self.main_p2_label_text_credentials.setGeometry(QtCore.QRect(130, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.main_p2_label_text_credentials.setFont(font)
        self.main_p2_label_text_credentials.setAlignment(QtCore.Qt.AlignCenter)
        self.main_p2_label_text_credentials.setObjectName("main_p2_label_text_credentials")
        self.main_p2_label_text_id = QtWidgets.QLabel(self.main_p2_frame)
        self.main_p2_label_text_id.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.main_p2_label_text_id.setFont(font)
        self.main_p2_label_text_id.setAlignment(QtCore.Qt.AlignCenter)
        self.main_p2_label_text_id.setObjectName("main_p2_label_text_id")
        self.main_p2_label_text_password = QtWidgets.QLabel(self.main_p2_frame)
        self.main_p2_label_text_password.setGeometry(QtCore.QRect(10, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.main_p2_label_text_password.setFont(font)
        self.main_p2_label_text_password.setAlignment(QtCore.Qt.AlignCenter)
        self.main_p2_label_text_password.setObjectName("main_p2_label_text_password")
        self.main_p2_btn_copy_id = QtWidgets.QPushButton(self.main_p2_frame)
        self.main_p2_btn_copy_id.setGeometry(QtCore.QRect(300, 60, 40, 21))
        self.main_p2_btn_copy_id.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n""")
        self.main_p2_btn_copy_id.setText("")
        icon1 = QtGui.QIcon()

        # set icons_copy.png path from your device
        icon1.addPixmap(QtGui.QPixmap(os.getcwd()+"./Icons/icons_copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_p2_btn_copy_id.setIcon(icon1)
        self.main_p2_btn_copy_id.setObjectName("main_p2_btn_copy_id")
        self.main_p2_btn_copy_id.setGeometry(QtCore.QRect(320, 62, 31, 21))
        self.main_p2_btn_copy_password = QtWidgets.QPushButton(self.main_p2_frame)
        self.main_p2_btn_copy_password.setGeometry(QtCore.QRect(320, 92, 31, 21))
        self.main_p2_btn_copy_password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n""")
        self.main_p2_btn_copy_password.setText("")
        self.main_p2_btn_copy_password.setIcon(icon1)
        self.main_p2_btn_copy_password.setObjectName("main_p2_btn_copy_password")
        self.main_p2_btn_reload = QtWidgets.QPushButton(self.main_p2_frame)
        self.main_p2_btn_reload.setGeometry(QtCore.QRect(150, 130, 71, 31))
        self.main_p2_btn_reload.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n""")
        self.main_p2_btn_reload.setText("")
        icon2 = QtGui.QIcon()

        # set icons_relaod.png path from your device
        icon2.addPixmap(QtGui.QPixmap(os.getcwd()+"./Icons/icons_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_p2_btn_reload.setIcon(icon2)
        self.main_p2_btn_reload.setIconSize(QtCore.QSize(20, 20))
        self.main_p2_btn_reload.setObjectName("main_p2_btn_reload")
        self.main_p2_label_id = QtWidgets.QLabel(self.main_p2_frame)
        self.main_p2_label_id.setGeometry(QtCore.QRect(100, 60, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.main_p2_label_id.setFont(font)
        self.main_p2_label_id.setAlignment(QtCore.Qt.AlignCenter)
        self.main_p2_label_id.setObjectName("main_p2_label_id")
        self.main_p2_label_password = QtWidgets.QLabel(self.main_p2_frame)
        self.main_p2_label_password.setGeometry(QtCore.QRect(140, 90, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.main_p2_label_password.setFont(font)
        self.main_p2_label_password.setAlignment(QtCore.Qt.AlignCenter)
        self.main_p2_label_password.setObjectName("main_p2_label_password")
        self.stackedWidget_Main.addWidget(self.stackedWidget_Main_page_2)
        self.label_project_title = QtWidgets.QLabel(self.centralwidget)
        self.label_project_title.setGeometry(QtCore.QRect(140, 0, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_title.setFont(font)
        self.label_project_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_title.setObjectName("label_project_title")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.stackedWidget_Main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Desktop Anywhrere"))
        self.main_p2_label_text_credentials.setText(_translate("MainWindow", "Credentials"))
        self.main_p2_label_text_id.setText(_translate("MainWindow", "ID:"))
        self.main_p2_label_text_password.setText(_translate("MainWindow", "Password:"))
        self.main_p2_label_id.setText(_translate("MainWindow", self.publicIP))
        self.main_p2_label_password.setText(_translate("MainWindow", self.password))
        self.label_project_title.setText(_translate("MainWindow", "Desktop Anywhere"))
